package com.bowt.backend.orderprocessing.infrastructure.persistence.jpa;

import com.bowt.backend.orderprocessing.application.util.OrderIdGenerator;
import com.bowt.backend.orderprocessing.domain.model.ShippingAddress;
import com.bowt.backend.orderprocessing.domain.model.enumeration.Currency;
import com.bowt.backend.orderprocessing.domain.model.enumeration.OrderStatus;
import com.bowt.backend.orderprocessing.domain.model.enumeration.PaymentMethod;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import lombok.Getter;
import lombok.Setter;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * ADR-001: BIGSERIAL surrogate pk (internal, JPA @Id) + UUIDv7 public handle `id`
 * (unique, generated by the application before save — this class only guards against
 * a null id with a fallback generator; it does not own generation).
 */
@Entity
@Table(name = "orders")
@Getter
@Setter
public class OrderEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "pk", insertable = false, updatable = false)
    private Long pk; // NEVER expose outside infrastructure — see ArchUnit rule in ADR-001

    @NotNull
    @Column(name = "id", nullable = false, unique = true, updatable = false)
    private UUID id;

    @NotNull
    @Column(name = "customer_id", nullable = false)
    private String customerId;

    @NotNull
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false)
    private OrderStatus status;

    @NotNull
    @Column(name = "total_amount", nullable = false)
    private BigDecimal totalAmount;

    @NotNull
    @Enumerated(EnumType.STRING)
    @Column(name = "currency", nullable = false)
    private Currency currency = Currency.USD;

    @Enumerated(EnumType.STRING)
    @Column(name = "payment_method")
    private PaymentMethod paymentMethod;

    @Column(name = "payment_transaction_id")
    private String paymentTransactionId;

    @Column(name = "idempotency_key", unique = true)
    private UUID idempotencyKey;

    @Embedded
    private ShippingAddressEmbeddable shippingAddress;

    @NotNull
    @Column(name = "created_at", nullable = false)
    private Instant createdAt;

    @NotNull
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    @Column(name = "confirmed_at")
    private Instant confirmedAt;

    @Column(name = "estimated_delivery_date")
    private LocalDate estimatedDeliveryDate;

    @Version
    @Column(name = "version", nullable = false)
    private Integer version;

    @OneToMany(mappedBy = "order", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.LAZY)
    private List<OrderItemEntity> items = new ArrayList<>();

    public OrderEntity() {
    }

    @PrePersist
    void prePersist() {
        if (this.id == null) {
            // Defensive fallback only — the application layer should always supply id
            // via OrderFactory. If this fires in practice, log it; it signals a caller bug.
            this.id = OrderIdGenerator.generate();
        }
        if (this.version == null) {
            this.version = 0;
        }
    }

    public void addItem(OrderItemEntity item) {
        items.add(item);
        item.setOrder(this);
    }

    public void clearItems() {
        items.clear();
    }
}